 trigger:
 pr: none

 parameters: 
   - name: certificatename
     displayName: create certificate 
     type: boolenan
     default: false

   -name: Environment
    displayName: select the environment
    type: string
    default: 'dev' 
    values:
      - "uat"
      - "pre-prod"
      - "prod"
      
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
  


