trigger:
  branches:
    include:
      - main
    exclude:
      - feature/*
pr: none

parameters: 
  - name: certificatename
    displayName: create certificate 
    type: boolean
    default: false

  - name: Environment
    displayName: select the environment
    type: string
    default: "dev" 
    values:
      - "uat"
      - "pre-prod"
      - "prod"

stages:
- stage: First
  jobs:  
    - job: Deploy
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            echo ${{parameters.Environment}}
            echo ${{parameters.certificatename}}
            echo 'Hello world'






