 trigger:
 pr: none

 parameters: 
   - name: certificatename
     displayName: create certificate 
     type: boolean
     default: false

   - name: Environment
     displayName: select the environment
     type: string
     default: 'dev' 
     values:
      - "uat"
      - "pre-prod"
      - "prod"
stages: 
  -stage:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'
  


