trigger:
  branches:
    include:
      - main
    exclude:
      - feature/*
pr: none

variables:
- group: Dev-varaible-Group
- name: display my name
  value: $(variables.name)

# steps:
# - script: echo $(name)

parameters: 
  - name: certificatename
    displayName: create certificate 
    type: boolean
    default: false

  - name: Environment
    displayName: select the environment
    type: string
    default: "uat" 
    values:
      - "uat"
      - "pre-prod"
      - "prod"      
stages:
- stage: First
  jobs:  
    - job: Deploy
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            echo ${{parameters.Environment}}
            echo ${{parameters.certificatename}}
            echo 'Hello world'
    #- job: Display my name
      - task:
      - script: echo $(myname)







