# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Bash Script'
  inputs:
    targetType: filePath
    filePath: './devicerreservation/reserve-device.sh'

- task: Bash@3
  displayName: 'Test'
  inputs:
    targetType: 'inline'
    script: |
      echo "---------------------------------"
      echo '$(successfulDeviceCount)'
      echo '$(successfulReservedDevices)'
      echo '$(devicesToDeAllocate)'

- task: Bash@3
  displayName: 'Bash Script'
  inputs:
    targetType: filePath
    filePath: './devicerreservation/deallocate-devices.sh'
    arguments: '-{successfulReservedDevices} "$(successfulReservedDevices)"'

