trigger:
  branches:
    include:
      - main
    exclude:
      - feature/*
pr: none

# steps:
# - script: echo $(myname)


parameters: 
  - name: Certificate_Update
    displayName: Certificate_ASDA 
    type: boolean
    default: false

parameters: 
  - name: certificatename
    displayName: create certificate 
    type: boolean
    default: false

  - name: Environment
    displayName: select the environment
    type: string
    default: "uat" 
    values:
      - "uat"
      - "pre-prod"
      - "prod"      
stages:
- stage: First
  jobs:  
    - job: Deploy
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            echo ${{parameters.Environment}}
            echo ${{parameters.certificatename}}
            echo 'Hello world'
    - job: Display
      steps:
      - script: echo $(myname)