# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

#- task: BatchScript@1
#  inputs:
#    filename: 'https://github.com/noudysri/Conflict-Demo/blob/main/reserve-device'
#    modifyEnvironment: false
#    workingFolder: '*'
  
- task: Bash@3
  inputs:
    filePath: 'https://github.com/noudysri/Conflict-Demo/blob/main/reserve-device.sh'
    workingDirectory: '.'
